### ISSUE TITLE
A non-null String must be provided to a Text widget

### ISSUE THREAD

**Issue by Andyhowe** [londonappbrewery/flash-chat-flutter#10]
Having error on 'The Flutter ListView' Video
so the flash chat only 1 data is appearing while the rest is cover by a red error box

`class MessageBubble extends StatelessWidget {
  MessageBubble({this.sender, this.text});

  final String sender;
  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(10.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        children: <Widget>[
          Text(
            sender,
            style: TextStyle(
              fontSize: 12.0,
              color: Colors.black54,
            ),
          ),
          Material(
            borderRadius: BorderRadius.circular(30.0),
            elevation: 5.0,
            color: Colors.lightBlueAccent,
            child: Padding(
              padding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
              child: Text(
                text,
                style: TextStyle(
                    color: Colors.white,
                    fontSize: 15.0
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
`

**Comment by telitabi** [comment]
![Screenshot_2020-01-01-23-17-00-503_co zawe flash_chat](https://user-images.githubusercontent.com/59417868/71644313-decf6e80-2cf4-11ea-903e-db9c090be276.jpg)

**Comment by Marvelxy** [comment]
You probably have a null text, check your firebase collection to make sure you don't have any empty fields.
