### ISSUE TITLE
Color for welcome screen ( 'Flash Chat' )

### ISSUE THREAD

**Issue by sam-tj** [londonappbrewery/flash-chat-flutter#16]
The color property is not available thus making it invisible due to white background.

**Comment by shubha360** [comment]
**Change this**

`return MaterialApp(
      theme: ThemeData.dark().copyWith(
        textTheme: TextTheme(
          body1: TextStyle(color: Colors.black54),
        ),
      ),`

**To this**
`return MaterialApp(
      theme: ThemeData.dark().copyWith(
        textTheme: TextTheme(
          bodyText2: TextStyle(color: Colors.black54),
        ),
      ),`

_Happy coding! :)_

**Comment by sbca98** [comment]
Hi @sam-tj you can add color property inside TextStyle and it should work.
