### ISSUE TITLE
No firebase app

### ISSUE THREAD

**Issue by farisdahleh** [londonappbrewery/flash-chat-flutter#25]
I followed all the steps in firebase configuration, every time I go to the registration page I got this error

"No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()"

**Comment by andreach36** [comment]
you need to call the initializeApp method on the Firebase class

you could use this function in the main.dart file instead of  void main() => runApp(FlashChat());

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(FlashChat());
}
