### ISSUE TITLE
using the animated text kit affects the text theme color

### ISSUE THREAD

**Issue by FredWolfe** [londonappbrewery/flash-chat-flutter#29]
After importing and using the text kit plugin, the Text becomes invincible, it can be seen disappearing in the background colour, this is really upsetting @angelabauer or anyone
any help fixing this problem?

**Comment by alainjr10** [comment]
> After importing and using the text kit plugin, the Text becomes invincible, it can be seen disappearing in the background colour, this is really upsetting @angelabauer or anyone
> any help fixing this problem?

I had the same problem. i just changed the text colour to black and it was all good.

**Comment by fobf** [comment]
add color: Colors.black, in the 
`AnimatedTextKit(
                  animatedTexts: [
                    TypewriterAnimatedText(
                      'Flash Chat',
                      textStyle: const TextStyle(
                        color: Colors.black,
                        fontSize: 45.0,
                        fontWeight: FontWeight.w900,
                      ),
                      speed: const Duration(milliseconds: 500),
                    ),
                  ],
                ),`
