### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by SuvrangshuBarua** [londonappbrewery/flash-chat-flutter#8]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2InternalException
: AAPT2 aapt2-3.2.1-4818971-windows Daemon #0: Daemon startup failed
  This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
 output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        64.0s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by MahmoudMabrok** [comment]
to solve androidx problems, please check this 
https://3alam.pro/mahmoudmabrok/articles/androidx-migration
